export const PREMIUM_TITLE_LARGE_FADE_RANGE = [0, 60] as const;
export const PREMIUM_TITLE_COMPACT_FADE_RANGE = [40, 80] as const;
export const PREMIUM_TITLE_COMPACT_TRANSLATE_Y = 20;
export const PREMIUM_TITLE_COMPACT_BLUR_RANGE = [0, 100] as const;
export const PREMIUM_TITLE_COMPACT_BLUR_MAX_INTENSITY = 50;
export const PREMIUM_TITLE_ACCESSIBILITY_SWITCH_AT = 60;
