export const HOME_TOOLBAR_CONTROL_SIZE = 44;
export const HOME_TOOLBAR_AVATAR_SIZE = 36;
export const HOME_TOOLBAR_HORIZONTAL_PADDING = 6;
export const HOME_TOOLBAR_GAP = 4;
export const HOME_TOOLBAR_WIDTH =
  HOME_TOOLBAR_CONTROL_SIZE * 2 + HOME_TOOLBAR_HORIZONTAL_PADDING * 2 + HOME_TOOLBAR_GAP;
